packages:
  - "apps/*"
  - "packages/*"

catalog:
  typescript: ^5
  eslint: ^9.39.2
  "@eslint/js": ^9.39.2
  typescript-eslint: ^8.46.0
  eslint-plugin-import-x: ^4.16.1
  eslint-import-resolver-typescript: ^3.10.1
