/**
 * Custom implementation of RFC 9457 Problem Details
 */
export interface ProblemDetails {
  /**
   * A URI reference that identifies the problem type.
   * When dereferenced, it provides human-readable documentation for the problem type.
   */
  type: string;
  /**
   * A short, human-readable summary of the problem type.
   * It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
   */
  title: string;
  /**
   * The HTTP status code generated by the origin server for this occurrence of the problem.
   */
  status: number;
  /**
   * A human-readable explanation specific to this occurrence of the problem.
   * This field is optional and provides additional details about the specific instance.
   */
  detail?: string;
  /**
   * A URI reference that identifies the specific occurrence of the problem.
   * It may or may not yield further information if dereferenced.
   */
  instance?: string;
}
